### ISSUE TITLE
Create image registry in Docker Hub and link it to this repository

### ISSUE THREAD

**Issue by secobau** [alejandro-colomar/dns#3]
To have available images to deliver.

**Comment by secobau** [comment]
https://hub.docker.com/u/alejandrocolomar

**Comment by secobau** [comment]
What is the exact location of the image repository?

**Comment by alejandro-colomar** [comment]
It was alejandrocolomar/dns

Now it is alejandrocolomar/bind

You can see it in the docker-compose
